Ginofrontjr
Programa-TrainIT-Ar/plataforma pull request #4
Opened 2023-09-28 12:24 UTC by GinoGallardo

*Cree la carpeta Moules.
*Agregue estilos al archivo module y cells.

Espero tus correcciones para mejorara, gracias.

2023-09-30 14:51 UTC, leonelgoncalves requested changes

2023-09-30 14:51 UTC, leonelgoncalves commented on src/app/(main)/modules/[name]/page.tsx
> +  const id = searchParams.get("id") - 1;
porque -1? el id no se debe de estar cambiando en el FE. El Id esta definido y cambiarlo va en contra de las reglas.

2023-09-30 14:51 UTC, leonelgoncalves commented on src/app/(main)/modules/[name]/page.tsx
> +  console.log(id);
remover este id

2023-09-30 14:51 UTC, leonelgoncalves commented on src/app/(main)/modules/[name]/page.tsx
> +            console.log(cell);
no deben haber console logs el codigo en master

2023-09-30 14:51 UTC, leonelgoncalves commented on src/app/(main)/modules/[name]/page.tsx
> +              <>
Porque necesitas un fragmento si hay un solo elemento?

2023-09-30 14:51 UTC, leonelgoncalves commented on src/app/(main)/modules/page.tsx
> +        ProductService.getModules().then((data) => setProducts(data));
porque esto esta llamando al product service? el productService era solo un ejemplo. Deberias crear un ModulesService y colocar el getModules alli

La variable de estado no deberia llamarse products porque estas guardando modulos

2023-09-30 14:51 UTC, leonelgoncalves commented on src/app/(main)/ButtonModules/ButtonModules.tsx
> +      ProductService.getCellModules().then((data) => setProducts(data));
porque esto esta llamando al product service? el productService era solo un ejemplo. Deberias crear un ModulesService y colocar el getModules alli

La variable de estado no deberia llamarse products porque estas guardando modulos

2023-09-30 14:51 UTC, leonelgoncalves commented on src/app/(main)/modules/[name]/page.tsx
> +    ProductService.getModules().then((data) => setProducts(data));
porque esto esta llamando al product service? el productService era solo un ejemplo. Deberias crear un ModulesService y colocar el getModules alli

La variable de estado no deberia llamarse products porque estas guardando modulos

2023-09-30 14:51 UTC, leonelgoncalves commented on src/demo/service/ProductService.tsx
> +    getModules() {
porque si esto esta llamando modulos esta en el servicio de productos? (este servicio era un ejemplo)

2023-09-30 14:51 UTC, leonelgoncalves commented on package.json
> +    "fake-api": "json-server --watch public/demo/data/modules.json --port 5000"
esto no deberia estar en la carpeta public. La carpeta public son cosas que van a ser subidas a produccion y no quieres que esto este en produccion. Porque no lo colocaste en la carpeta stubs con los demas stubs?

2023-11-18 13:18 UTC, GinoGallardo commented
Cree estructura de login y crear module.

2023-11-29 13:53 UTC, leonelgoncalves approved these changes

2023-11-29 13:54 UTC, merged