feature: user profile
Programa-TrainIT-Ar/plataforma pull request #5
Opened 2023-09-29 15:59 UTC by joshvader

Creación de la vista de los datos del usuario. Sin bien me muestra la respuesta 200 al correr npm run stubs y haciendo el llamado con useEffect al servicio getUsers no muestra los datos en pantalla. Tampoco me arroja error por consola o por Visual Code. 
Si hay algo que faltó me lo hacen saber.

2023-09-30 15:01 UTC, leonelgoncalves requested changes

2023-09-30 15:01 UTC, leonelgoncalves commented on src/app/(main)/user/page.tsx
> +                                <h5 id="name-user">{user?.username}</h5>
todo este contenido deberia estar dentro de un if que valida si el usuario esta definido. Porque si no lo esta estas mostrando un monton de campos que no tienen nada y es raro

2023-09-30 15:01 UTC, leonelgoncalves commented on src/app/(main)/user/page.tsx
> +useEffect(() => {
porque el archivo no esta identado?

2023-10-01 02:46 UTC, joshvader commented on src/app/(main)/user/page.tsx
> +    UsersService.getUsers().then(res => setUser);
Modifique usando UsersService.getUsers().then(setUser);

2023-10-01 02:46 UTC, joshvader commented on src/app/(main)/user/page.tsx
> +                                <h5 id="name-user">{user?.username}</h5>
agregue un operador ternario para que cumpla con la condición.

2023-11-01 04:57 UTC, leonelgoncalves approved these changes

2023-11-01 04:57 UTC, merged